apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: nodejs-application
  name: nodejs-application
  namespace: nodejsapplication
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nodejs-application
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
