apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodejs
    app.kubernetes.io/name: nodejs-application
  name: nodejs
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: metrics
  selector:
    app: nodejs
  type: NodePort
status:
  loadBalancer: {}
